### ISSUE TITLE
Non-static methods making access checks complicated

### ISSUE THREAD

**Issue by dschach** [codefriar/CanTheUser#1]
Would it be better to make these methods static?
The main class says we can use `if(CanTheUser.read(new account())){}` but the unit tests say `new CanTheUser().create(new Account())`
I vote for **static** because it should be checked every time. I'm less concerned about users receiving permission set assignments "in the middle" of this because this check happens quickly and I assume that the memoizedFLSResults` variable would not be called both before and after a separate dml to insert the permission set assignment.

**Comment by dschach** [comment]
Upon further thinking, maybe it's best to make the code run as the tests do, not as the description says.

**Comment by codefriar** [comment]
@dschach 

I'm torn on this. As you can see from the comments, it was originally written as static methods. But the older i get the more I want things to be instance methods. 

we can always run 
```
if(new CanTheuser.read(new foo())){...
``` 

thoughts?

**Comment by dschach** [comment]
The downside of instance methods include that it is VERY awkward to assert a negative on them. And it's just more characters.
Funny that the more I code, the more I just want things static so I can refer to them once, in fewer characters. 
I'm honestly torn here. I just don't use the word `new` unless necessary, and I don't ever use instance methods for describe classes. ActionPlans has all its describe calls static, and it streamlines the code.

**Comment by codefriar** [comment]
Seems like a great opp to do it both ways!

**Comment by dschach** [comment]
He's right... and he's right... why can't they both be right??? 

I love it.

**Comment by dschach** [comment]
After giving it some more thought: Static means we can't chain methods. But do we need to chain methods? If we include CanTheUser methods in Safely, then we combine all the checks in one place and don't need to chain anything.

Can you think of a reason to chain methods here? If not, then I'm heavily leaning to static just because we are executing this once and then moving on.

**Comment by dschach** [comment]
Just watched your codelive video with @rsoesemann and I see some of his points. But I do still think that with describe classes and simple methods that just return unchanging values, static methods are a good way to go. But that's just me :)
