### ISSUE TITLE
Safely should fail gracefully or call CanTheUser in its methods

### ISSUE THREAD

**Issue by dschach** [codefriar/CanTheUser#2]
https://github.com/codefriar/CanTheUser/blob/853b1a211282db190b86aa924ecc70df11ff8f82/force-app/main/default/classes/Safely.cls#L92

While I have no problem doing CanTheUser.edit() before doing Safely DML, could we save a line here and there and put CanTheUser into the Safely methods? That way, Safely could fail more gracefully if we try to do an update and the user doesn't have that permission.

**Comment by codefriar** [comment]
@dschach 

it's not very clear in the code, but the SOBjectAccessDecision created by the guard method does enforce CRUD checking as well. See:
https://github.com/codefriar/CanTheUser/blob/853b1a211282db190b86aa924ecc70df11ff8f82/force-app/main/default/classes/Safely.cls#L114 

Safely().doInsert() is effectively checking crud, and inserting all the fields the user has write access too (and alternatively throwing when the code tries to write to a field that the user doesn't have write permission to.

**Comment by dschach** [comment]
As written in your code, it fails if the user has no access to the entire object. I think that's the big thing: What do we do if you try to insert an account and can't see that the object exists? So I added a check on each method; it's in the pull request.
