### ISSUE TITLE
Unnecessary lines in doQuery?

### ISSUE THREAD

**Issue by dschach** [codefriar/CanTheUser#4]
Because doQuery calls guardAgainstRemovedFields, the exception will be thrown in guardAgainstRemovedFields, and there is no way to reach the exception in doQuery. If the fields are readable, it won't throw the exception. And if the fields are updateable, they are also readable, so it won't throw the exception.

I'm submitting the pull request with those lines commented. Please see what you think about that, and if you agree, I think we can delete the lines.

**Comment by codefriar** [comment]
Good catch. Removed.
