### ISSUE TITLE
Why is the crud method public? Should we force people to call the individual DML methods?

### ISSUE THREAD

**Issue by dschach** [codefriar/CanTheUser#6]
https://github.com/codefriar/CanTheUser/blob/39850d02c05d75e2cb7a71d4c80b53ddb06067c1/force-app/main/default/classes/CanTheUser.cls#L54

Perhaps we make the crud() methods private and remove direct calls to them from the test class.

Do we expect users to call the crud methods directly, or do we expect them only to call the "special" methods such as `create`, `read`, etc?

**Comment by codefriar** [comment]
You're right. I'd originally left it public for ... hell if I remember. wanna pr it, or leave it to me?

**Comment by codefriar** [comment]
actually I'm taking care of it.

**Comment by codefriar** [comment]
I made it private, but also @testVisible
